In [2]:
import pandas as pd
import numpy as np

# Creating dataframe from an array

# Option 1

In [4]:
# creating an array
data = np.array([[1, 4], [2, 5], [3, 6]])

In [7]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])

In [10]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Option 2

In [11]:
# creating an array with list shape
data = [[1, 4], [2, 5], [3, 6]]

In [12]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])

In [13]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Creating a DataFrame from a dictionary

In [16]:
# lists used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [39613493, 29730311, 21944577, 19299981]

In [17]:
# storing lists within a dictionary
dict_states = {'Sates': states , 'Population': population }

In [18]:
# creating the dataframe
df_population = pd.DataFrame(dict_states)

In [20]:
# showing the dataframe
df_population

        Sates  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

# Creating a DataFrame from a csv file

In [28]:
# reading the csv file
df_exams = pd.read_csv("../data/StudentsPerformance.csv")

In [30]:
# show first 5 rows in a dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86