In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv("../data/StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Adding a new column

## Adding a new column with scalar value

In [3]:
# adding new column to dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

## Adding a new column with an array

The dataframe has 1000 rows, so we need to create an array with 1000 elements

In [6]:
# import numpy
import numpy as np

In [11]:
# create an array of 1000 elements
language_score = np.arange(0, 1000)

In [12]:
# length of the array
len(language_score)

1000

In [16]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [24]:
# create random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size=1000)

In [27]:
# min value inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

np.int64(99)

In [29]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,57
1,female,group C,some college,standard,completed,69,90,88,22
2,female,group B,master's degree,standard,none,90,95,93,80
3,male,group A,associate's degree,free/reduced,none,47,57,44,9
4,male,group C,some college,standard,none,76,78,75,2
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,83
996,male,group C,high school,free/reduced,none,62,55,55,52
997,female,group C,high school,free/reduced,completed,59,71,65,22
998,female,group D,some college,standard,completed,68,78,77,79
999,female,group D,some college,free/reduced,none,77,86,86,73

In [31]:
# create random float numbers between 1 and 100
np.random.uniform(1, 100, size=100)

array([99.09844702, 53.58100314, 38.29385085, 85.62239517, 97.18403856,
       80.82022039, 34.02587486, 44.69977493, 85.1699782 , 65.34031172,
       49.98022012, 78.6826458 , 62.57019358,  2.55737688, 79.68682194,
        7.92206725, 52.52639692, 59.96586321, 50.1736423 , 18.78375625,
       60.72364245, 24.0058114 , 62.79053971, 46.80567485, 13.05577781,
       10.23041022, 37.9865799 , 12.14733505, 69.71756916, 57.84477619,
        2.27059004, 43.69215691,  4.43453903, 42.92426081, 26.43982486,
       57.80300422, 92.29752478, 27.46119529,  5.77389888, 53.80879214,
       42.60943643, 68.328298  , 32.43071117, 39.11350451, 18.9489481 ,
       57.13621667, 80.05427814, 67.56598027, 77.0412767 , 90.08976376,
       36.03701285, 91.97981134, 59.82729596, 52.42154086, 55.89632666,
       21.07917729, 86.5134133 , 52.60454597, 92.27160198, 21.51235162,
       32.27513464, 43.52051582, 29.33506665,  3.49104342, 24.65444334,
       47.01346371, 85.60546601, 60.45408413, 35.97913965, 20.47430237,
       57.39054618, 55.33505098, 98.41701686, 41.01361452,  1.21434846,
       40.44616655, 74.21514522, 50.24080561, 63.98590424,  7.16766893,
       74.52171853, 94.49845108,  6.8911856 , 78.30296878, 30.1279122 ,
       98.67151054, 93.01767262, 40.53827997, 85.12050935,  7.08227703,
       43.58789017, 64.21327644, 98.94715021, 52.94521561,  7.65931722,
       17.36113794, 87.76814924, 58.15691567, 14.83260706, 47.66312912])

## Adding new column with assign() method

When to use assign?
- Add multiple columns in a single line of code
- When you need to overwrite the values of an existing columns (best practice)

It returns a new object (a copy) with all the original columns in addition to the new ones

In [42]:
# create random numbers for our new score columns
score1 = np.random.randint(1, 100, size = 1000)
series1 = pd.Series(score1, index=np.arange(0, 1000))

In [44]:
# create a series using the random numbers
score2 = np.random.randint(1, 100, size = 1000)
series2 = pd.Series(score1, index=np.arange(0, 1000))

In [47]:
# using assign() to add multiple columns
df_exams = df_exams.assign(score1=series1, score2=series2)

In [49]:
# show dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,57,40,13
1,female,group C,some college,standard,completed,69,90,88,22,54,12
2,female,group B,master's degree,standard,none,90,95,93,80,60,49
3,male,group A,associate's degree,free/reduced,none,47,57,44,9,6,90
4,male,group C,some college,standard,none,76,78,75,2,83,2
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,83,3,45
996,male,group C,high school,free/reduced,none,62,55,55,52,45,15
997,female,group C,high school,free/reduced,completed,59,71,65,22,29,48
998,female,group D,some college,standard,completed,68,78,77,79,28,94
999,female,group D,some college,free/reduced,none,77,86,86,73,5,76

## insert()

Inserts a new column at a specific position or index

In [53]:
# using index() to add a column at a specific position
df_exams.insert(1, 'test', series1)

In [54]:
# show dataframe
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,40,group B,bachelor's degree,standard,none,72,72,74,57,40,13
1,female,54,group C,some college,standard,completed,69,90,88,22,54,12
2,female,60,group B,master's degree,standard,none,90,95,93,80,60,49
3,male,6,group A,associate's degree,free/reduced,none,47,57,44,9,6,90
4,male,83,group C,some college,standard,none,76,78,75,2,83,2
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,3,group E,master's degree,standard,completed,88,99,95,83,3,45
996,male,45,group C,high school,free/reduced,none,62,55,55,52,45,15
997,female,29,group C,high school,free/reduced,completed,59,71,65,22,29,48
998,female,28,group D,some college,standard,completed,68,78,77,79,28,94
999,female,5,group D,some college,free/reduced,none,77,86,86,73,5,76